security:
  oauth2:
    client:
      clientSecret: ${GOOGLE_SECRET}

spring:
  datasource:
    url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}
    username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
    password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
  thymeleaf:
    cache: true

logging:
  file: ${OPENSHIFT_DIY_LOG_DIR}/tracker.log
  level: info
