security:
  oauth2:
    client:
      clientId: 539913688449-662gsf3b7uuu1m8j4dlt10hbftjfi7mt.apps.googleusercontent.com
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true

spring:
  datasource:
    platform: hsqldb
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

management:
  context-path: /manage

quit-tracker:
  date-format: MM/dd/yyyy
---
spring:
  profiles: openshift
  datasource:
    url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}
    username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
    password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
  thymeleaf:
    cache: true

security:
  oauth2:
    client:
      clientSecret: ${GOOGLE_SECRET}

logging:
  file: ${OPENSHIFT_DIY_LOG_DIR}/tracker.log
  level: info

